### ISSUE TITLE
Updating the relaystore does not trigger a rerender of a scene in tabbar

### ISSUE THREAD

**Issue by proProbe** [r0b1n/rnrf-relay-renderer#14]
Hello! I currently have problems with changes in the relaystore not actually rerender a scene in tabbars. It works quite well with new scenes but with static scenes such as the tabbar-scenes nothing changes

**Comment by cxyokk** [comment]
Related ticket: https://github.com/aksonov/react-native-router-flux/issues/437#issuecomment-254044469

**Comment by sibelius** [comment]
U can use Actions.refresh() after u change ur store

**Comment by proProbe** [comment]
@sibelius I actually tried using refresh. It did not work.

**Comment by sibelius** [comment]
This is the code I'm using to refresh my routes after my networklayer changes, the reset method of my RelayStore creates a new Relay.Environment when  I change the network layer

``` jsx
updateToken(token) {
    AsyncStorage.setItem('token', token);

    if (token === '' || token === null) {
      const networkLayer = new Relay.DefaultNetworkLayer(config.graphlURL);
      relayStore.reset(networkLayer);

      AsyncStorage.clear();
    } else {
      const networkLayer = new Relay.DefaultNetworkLayer(
        config.graphlURL, {
          headers: {
            authorization: token,
          }
        });
      relayStore.reset(networkLayer);
    }

    this.setState({
      token,
    });

    // Refresh current router after reset
    Actions.refresh();
  }
```

``` jsx
<Router
          scenes={scenes}
          environment={relayStore}
          updateToken={this.updateToken.bind(this)}
          renderLoading={this.renderLoading}
        />
```

``` jsx
reset(networkLayer) {
    if (networkLayer !== undefined) {
      this._networkLayer = networkLayer;
    }

    this._env = new Environment();
    if (this._networkLayer !== null) {
      this._env.injectNetworkLayer(this._networkLayer);
    }
    if (this._taskScheduler !== null) {
      this._env.injectTaskScheduler(this._taskScheduler);
    }

    RelayNetworkDebug.init(this._env);
  }
```

**Comment by proProbe** [comment]
@sibelius yeah Ive gotten that to work. Im using a switch between `login` and my main `app` where environment is changed between. I havent done anything to the networklayer though. should this always be reset? I thought it did it by itself.

My problem is mainly when Im in `tab1` and mutate some data related to `tab2`, nothing happens when I jump back to `tab2`

**Comment by sibelius** [comment]
u should use the same RelayStore for `login` and `app` and u should reset the environment after login or on logout

take a look on my custom relayStore: https://gist.github.com/sibelius/7d7f691dbc2cb676750805db853dab80

u should call reset after login or logout

**Comment by proProbe** [comment]
Looks superfancy and cool. Im not sure how that will solve my problems though as it doesnt have anything with the resetting of the environment to do. Im already in my `Main app` and have two tabs `tab1` and `tab2`. `tab1` mutates the data and `tab2` needs to change according to this data. Using refresh does rerender `tab2` but doesnt seem to rerender it with the correct data.

**Comment by rgovindji** [comment]
@sibelius Couple of questions because I'm running into a few odd issues that may be related. 
- Why is it good practice to reset the relay store on login?
- Should I reset the store, every time the app starts up? ( Login doesn't occur often because I'm using a long lived JWT )
- Should Actions.refresh() be called after every mutation or every time new data is ingested? 
- Where do you put Actions.refresh(), in componentWillReceiveProps()?

**Comment by sibelius** [comment]
1. Relay.Environment store all the cached information, so after an user logout, u should clean the cache, so an authorized user do not see that data.
2. U should only reset it when there is a Login or Logout
3. `Actions.refresh()` is only need after u reset the relay.environment of ur RelayStore
4. `Actions.refresh()` should come after `RelayStore.reset()`

Note, `Actions.refresh()` is not always needed

**Comment by rgovindji** [comment]
Thanks really appreciate it!

**Comment by rgovindji** [comment]
@sibelius if I chose to use your custom RelayStore.js instead of the default Relay.Store does that mean I would have to update all my mutations from Relay.Store.commitUpdate to relayStore.commitUpdate?

**Comment by sibelius** [comment]
this.props.relay inside ur components will always be equals ur RelayStore that u pass in environment of this package.

U should use custom store if u don't have acess to this.props.relay
