### ISSUE TITLE
Working with tabs

### ISSUE THREAD

**Issue by Naoto-Ida** [r0b1n/rnrf-relay-renderer#18]
I currently have `react-native-router-flux`'s tabs wrapping a few components.
In one of them, I have another implementation of tabs using [react-native-scrollable-tabview](https://github.com/skv-headless/react-native-scrollable-tab-view).

Each tab inside of the tabbed section has a query, but cannot be run and are stuck in a loading state
.
Is there any support for non-top level queries?

**Comment by sibelius** [comment]
@Naoto-Ida if u wanna move to React Navigation

u can check it out how to use with Relay here: https://github.com/sibelius/ReactNavigationRelay/blob/master/src/RelayUtils.js#L67

**Comment by Naoto-Ida** [comment]
Hey @sibelius, thanks again for your suggestion!
I might give it a try since it seems, by your example, I can have individual queries inside of the tab inside a `react-native-router-flux` tab.

**Comment by Naoto-Ida** [comment]
@sibelius I want to ask you directly, but I'll continue on this thread.
Will your implementation of the RelayUtils work without the need of React Navigation?
The issue I'm having is one of those "one-off" things where I have a component which has multiple components(tabs) inside of it which require different queries.

**Comment by sibelius** [comment]
It does work without react navigation. It will create a Relay.Renderer much like this package

**Comment by Naoto-Ida** [comment]
@sibelius  Ah, thanks. I got it working.
Is it possible to use the same Relay environment (is that terminology correct?) that the rnrf-relay-renderer is using?

**Comment by sibelius** [comment]
Yep, Just change the RelayUtils code
