### ISSUE TITLE
Infinite render calls after Action.refresh

### ISSUE THREAD

**Issue by antonsivogrivov** [r0b1n/rnrf-relay-renderer#3]
A have a component like

```
class MyScene extends Component {
    componentWillMount() {
         Actions.refresh({
             renderTitle: this.renderTitle,
             renderBackButton: this.renderBackButton,
         });
    }

    render() {
        return (
            <View>
               // some content
            </View>
        );
    }
}

export default Relay.createContainer(MyScene, {
    initialVariables: {},
    fragments: {
        viewer: () => Relay.QL
            fragment on User {},
    },
});
```

Moving to rnrf-relay-renderer in my project, I encountered a strange behavior.

Call Action.refresh leads to multiple infinite calls of render() func of MyScene component and my react native app doesn't response anymore.

Any ideas?

**Comment by r0b1n** [comment]
@tonygriv thanks for feedback.

It is interesting, I will try to reproduce this.
Which versions of react-native, router and relay do you use?

**Comment by antonsivogrivov** [comment]
I use:
react-native: 0.26.2
react-native-router-flux: 3.26.5
react-relay: 0.8.1

**Comment by antonsivogrivov** [comment]
Hmm... I have updated relay from 0.8 to 0.9 and seems everything is working good.
