### ISSUE TITLE
Only one default export allowed per module.

### ISSUE THREAD

**Issue by rturk** [r0b1n/rnrf-relay-renderer#6]
RelayComponentRenderer is exporting two default objects, and this causes a violation error.

L11 and L60

Here:
https://github.com/r0b1n/rnrf-relay-renderer/blob/master/src/RelayComponentRenderer.js#L11
And Here:
https://github.com/r0b1n/rnrf-relay-renderer/blob/master/src/RelayComponentRenderer.js#L60

**Comment by rturk** [comment]
FYI. As a reference patched here:
https://github.com/rturk/rnrf-relay-renderer/tree/patch-1

**Comment by masterkrang** [comment]
@rturk i actually added your patch and now my repo is busted it looks like it's deleted...

**Comment by r0b1n** [comment]
Thank you @rturk !
I've pushed new version to `github` and `npm` moments ago.
