### ISSUE TITLE
`Initial` boolean for Scenes could be ignored?

### ISSUE THREAD

**Issue by Naoto-Ida** [r0b1n/rnrf-relay-renderer#8]
So currently my main component looks like this:

``` js
<Router
  createReducer={reducerCreate}
  wrapBy={RelayRenderer()}
>
  <Scene key="root">
    <Scene
      key="articleList"
      component={ArticleListContainer}
      title="Articles"
      initial={true}
      queries={{viewer: () => Relay.QL`query { viewer } `,}}
    />
    <Scene
      key="showArticle"
      component={ArticleContainer}
      hideTabBar={true}
      queries={{node: () => Relay.QL`query { node(id: $nodeID) } `,}}
    />
  </Scene>
</Router>
```

Inside of `ArticleListContainer` I'm doing something like this:

`Actions.showArticle({nodeID: this.props.data.id})}`

It seems like the query for `ArticleContainer` is run and  `ArticleListContainer` is ignored.
Has anybody experienced this? It seems like the example code should run into that issue too, seeing as theres two `Scene`s inside of the `Scene` with the key `root`.

**Comment by sibelius** [comment]
Try Actions.refresh()

**Comment by Naoto-Ida** [comment]
@sibelius 

As in `componentWillMount()`? In both components?
